### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by aveao** [CaitSith2/SwitchSDTool#1]
Heyo!

Just wanted to let you know that your project doesn't have a license. This means that you own the copyright to the code, and this isn't good (at least from an open source developer's perspective), here's why in the words of [choosealicense.com](https://choosealicense.com/no-permission/):

> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.

Can you please add a license to your code? I recommend either using MIT or GPLv2.

**Comment by CaitSith2** [comment]
Fixed in baf446a3218c08ae62ffe6b11ea638fbe9e5d6b0
