### ISSUE TITLE
[Feature Requests] Automatic Key Loading from TXT File + NCA File Name Display

### ISSUE THREAD

**Issue by sora10pls** [CaitSith2/SwitchSDTool#2]
The basic idea behind these two feature requests is as follows.

### Automatic Key Loading from a TXT File
If this feature is added to the program, it would save a little bit of time for the user to have to enter in ETICKET RSA KEK every single time the program is run. Something like if a file named `eticket.txt` exists in the working directory, load the contents of that file into the textbox.

If this is out of the question, the program could even just save the ticket in some type of settings file that doesn't require the user to enter said key every time the program is run.

### NCA File Name Display
This feature is simply for convenience, as it would be very helpful to know which NCA file corresponds to which title. In the Games window, below the title name, ideally it would also display the name of the corresponding NCA.

For example, in the attached picture below, in that red highlighted area the program would display `41d3ee61e0adbc2465d0648ec02a0c80.nca` (the NCA file name for Mario Kart 8 Deluxe Update Data) to the user.
![image](https://user-images.githubusercontent.com/17801814/44223974-2cc2f100-a157-11e8-996f-ef0d73c848f6.png)

Thanks again for this great tool! It's very well put together and the UI is awesome.

**Comment by CaitSith2** [comment]
For the eticket_rsa_kek, the program already does this.  In fact, if you close and reopen, then click on load key, it will just do that silently.

As for NCA File Name display, I could in fact add that in, however, there are actually several NCA files present per given title.  I could indeed list them.

**Comment by sora10pls** [comment]
Cool, I had no idea it was stored locally in `Configuration.json`. Thanks for the heads up, and thank you in advance for adding in my second request!
