### ISSUE TITLE
Big NSP Games >4GB cannot dumping -v1.09

### ISSUE THREAD

**Issue by RyuSeisuke1992** [CaitSith2/SwitchSDTool#4]
please fix.

**Comment by SADXfan01** [comment]
No idea where Cait is, great tool, but this is a particularly big problem. For now, just use 1.07. It is significantly slower, but should still get the job done in the end. All release binaries pre-1.09 were removed for some reason, so here's one I found.

https://drive.google.com/file/d/13IhICBss8cZHriAAKv4bvkHE9iWTMkzp/view?usp=sharing

**Comment by CaitSith2** [comment]
Fixed in https://github.com/CaitSith2/SwitchSDTool/releases/tag/1.10
